### ISSUE TITLE
An Error during pulling progress

### ISSUE THREAD

**Issue by AxadjonovOyatillo21** [AbduazizZiyodov/docker-dashboard#3]
3. Using the dashboard I found the Postgres image and pressed the pull button. During pulling progress I moved to the containers/images page, but there is nothing. And I checked using docker if images/containers really exist. And it was an error of the app. No problem docker. Then tried to refresh the page, and got an error. 
![image](https://user-images.githubusercontent.com/74463827/179972237-a1f6ca12-d5cb-4faa-ab72-1589709fa949.png)
Looks like, the error is in API. I've requested images during pulling progress and API still not responding now. 
![image](https://user-images.githubusercontent.com/74463827/179972637-4c4f604f-8ada-443c-a3f0-a86413180b18.png)
It responded when pulling finished.
![image](https://user-images.githubusercontent.com/74463827/179973516-d4ad3d27-ec3d-4002-a824-0ebb151adc5e.png)
But, After this, I realized that there is no problem with docker lib. Maybe the problem is with async or web framework, I don't know. But fixing this issue will be good. Or is this error only on my machine?

**Comment by AbduazizZiyodov** [comment]
I am working on a new mechanism for pulling images. It will be fixed & implemented in the next releases.
